# Generated by Django 2.0.7 on 2018-10-15 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 13, 6, 30, 701534, tzinfo=utc)),
        ),
    ]
