# Generated by Django 2.0.7 on 2018-10-17 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20181017_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 17, 11, 53, 28, 608583, tzinfo=utc)),
        ),
    ]
